# Organization Metadata
title = "The NASA ODSI Contributor Network"
description = "An interactive visualization of the reach and impact of NASA ODSI's contributions to open source repositories."
organization_name = "NASA ODSI"
organization_nickname = "ODSI"
og_url = "https://developmentseed.github.io/nasa-odsi-contributor-network/"
og_image = "https://developmentseed.github.io/nasa-odsi-contributor-network/site-image.jpg"
theme_color = "#133966"

# Repositories
repositories = [
"apache/arrow-rs",
 "boettiger-lab/earthdatalogin",
 "conda-forge/r-lasr-feedstock",
 "cloudnativegeo/cloud-optimized-geospatial-formats-guide",
 "datafusion-contrib/arrow-zarr",
 "earth-mover/icechunk",
 "flatgeobuf/flatgeobuf",
 "geoarrow/deck.gl-layers",
 "geoarrow/geoarrow-rs",
 "geopandas/geopandas",
 "georust/geo-svg",
 "holoviz/hvplot",
 "jupyterhub/repo2docker",
 "pangeo-data/pangeo-docker-images",
 "pangeo-data/pangeo.io",
 "nasa/python_cmr",
 "nasa-openscapes/earthdata-cloud-cookbook",
 "nsidc/earthaccess",
 "nsidc/cloud-optimized-icesat2",
 "numbagg/numbagg",
 "pydata/xarray",
 "radiantearth/stac-spec",
 "stac-extensions/zarr",
 "stac-utils/stac-fastapi-pgstac",
 "stac-utils/rustac-py",
 "stac-utils/pgstac",
 "stac-utils/pystac",
 "stac-utils/pystac-client",
 "stac-utils/xpystac",
 "virtual-zarr/hrrr-parser",
 "virtual-zarr/virtual-tiff",
 "virtual-zarr/obspec-utils",
 "zarr-developers/zarr-python",
 "zarr-developers/geozarr-spec",
 "zarr-developers/VirtualiZarr",
 "2i2c-org/jupyterhub-fancy-profiles",
]

[branding]
primary_color = "#133966"
secondary_color = "#2A79DB"
text_color = "#000000"

# Core organization contributors
[contributors.core]
AliceR = "Alice Rühl"
abarciauskas-bgse = "Aimee Barciauskas"
aboydnw = "Anthony Boyd"
aliziel = "Ali Z"
alukach = "Anthony Lukach"
anayeaye = "Alexandra Kirk"
batpad = "Sanjay Bhangar"
benbovy = "Benoît Bovy"
bitner = "David Bitner"
botanical = "Jennifer Tran"
brianna-corremonte = "Brianna Corremonte"
camillecroft = "Camille Owens"
ceholden = "Chris Holden"
chuckwondo = "Chuck Daniels"
ciaransweet = "Ciaran Sweet"
danielfdsilva = "Daniel da Silva"
d-v-b = "Davis Bennett"
dzole0311 = "Gjore Milevski"
emmalu = "Emma Paz"
faustoperez = "Fausto Pérez"
gadomski = "Pete Gadomski"
hanbyul-here = "Hanbyul Jo"
hrodmn = "Henry Rodman"
ifsimicoded = "Simi Damani"
indraneel = "Indraneel Purohit"
ividito = "Isayah Vidito"
j08lue = "Jonas Sølvsteen"
jjfrench = "Jamison French"
jsignell = "Julia Signell"
jbusecke = "Julius Busecke"
kamicut = "Marc Farra"
kylebarron = "Kyle Barron"
leothomas = "Leo Thomas"
lillythomas = "Lilly Thomas"
lhoupert = "Loïc Houpert"
maxrjones = "Max Jones"
martham93 = "Martha Morrissey"
moradology = "Nathan Zimmermann"
negin513 = "Negin Sobhani"
sandrahoang686 = "Sandra Hoang"
sharkinsspatial = "Sean Harkins"
smk0033 = "Sheyenne Kirkland"
smohiudd = "Saadiq Mohiuddin"
srmsoumya = "Soumya Ranjan Mohanty"
sunu = "Tarashish Mishra"
vgeorge = "Vitor George"
vincentsarago = "Vincent Sarago"
weiji14 = "Wei Ji"
wildintellect = "Alex I. Mandel"
willemarcel = "Wille Marcel"
wrynearson = "Will Rynearson"
yellowcap = "Daniel Wiesmann"
zacdezgeo = "Zac Deziel"
